#!/bin/sh
################################################################################
#      This file is part of LibreELEC - https://libreelec.tv
#      Copyright (C) 2016 Team LibreELEC
#      Copyright (C) 2016 Mateusz Krzak (kszaquitto@gmail.com)
#
#  OpenELEC is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  OpenELEC is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

SOURCEREMOTECONF=""
TMPREMOTECONF="/tmp/remote.conf"
REMOTECONFPRESENT="yes"
REMAP="no"

if [ -f /storage/.config/remote.conf ]; then
  SOURCEREMOTECONF="/storage/.config/remote.conf"
  REMAP="yes"
elif [ -f /flash/remote.conf ]; then
  SOURCEREMOTECONF="/flash/remote.conf"
  REMAP="yes"
elif [ -f /etc/amremote/remote.conf ]; then
  SOURCEREMOTECONF="/etc/amremote/remote.conf"
elif ! grep -q /dev/system /proc/mounts ; then
  mount -o rw,remount /flash
  mkdir -p /tmp/system
  mount -o ro /dev/system /tmp/system
  if [ -f /tmp/system/etc/remote.conf ] ; then
    cp /tmp/system/etc/remote.conf /flash/remote.conf
    SOURCEREMOTECONF="/flash/remote.conf"
  elif [ -f /tmp/system/remote.conf ] ; then
    cp /tmp/system/remote.conf /flash/remote.conf
    SOURCEREMOTECONF="/flash/remote.conf"
  fi
  umount /tmp/system
  REMAP="yes"
else
  REMOTECONFPRESENT="no"
fi

if [ "$REMOTECONFPRESENT" = "yes" ]; then
  cp "$SOURCEREMOTECONF" "$TMPREMOTECONF"
  if [ "$REMAP" = "yes" ]; then
    sed -i -E 's/\s15(#.*|$)/ 1\1/
            s/\s63(#.*|$)/ 90\1/
            s/\s97(#.*|$)/ 28\1/
            s/\s102(#.*|$)/ 172\1/
            s/\s104(#.*|$)/ 115\1/
            s/\s109(#.*|$)/ 114\1/
            s/\s125(#.*|$)/ 46\1/
            s/\s142(#.*|$)/ 116\1/
            s/\s143(#.*|$)/ 116\1/
            s/\s158(#.*|$)/ 1\1/
            s/\s183(#.*|$)/ 59\1/
            s/\s184(#.*|$)/ 399\1/
            s/\s185(#.*|$)/ 400\1/
            s/\s186(#.*|$)/ 60\1/
            s/\s232(#.*|$)/ 38\1/
            s/\s240(#.*|$)/ 164\1/
            s/\s241(#.*|$)/ 128\1/
            s/\s242(#.*|$)/ 163\1/
            s/\s243(#.*|$)/ 165\1/
            s/\s244(#.*|$)/ 208\1/
            s/\s245(#.*|$)/ 168\1/
            s/\s264(#.*|$)/ 63\1/
            s/\s704(#.*|$)/ 116\1/' "$TMPREMOTECONF"
  fi
  /usr/bin/remotecfg "$TMPREMOTECONF"
fi
